version: '3.9'

services:

  # postgres 資料庫
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: wits
      POSTGRES_PASSWORD: ilovewits
      POSTGRES_DB: wits_db
    ports:
      - 5432:5432
    volumes:
      - ./pgsql :/var/lib/postgresql/data

  
  # MySQL 資料庫
  mysql:
    container_name: mysql
    # image: mysql:5.7
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql :/var/lib/mysql

  # Redis 服務
  reids:
    container_name: redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data


  # 陽春DB browser
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 5566:8080